# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Final Test Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Final Test Project

  target 'Final Test ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Final Test ProjectUITests' do
    # Pods for testing
  end

end
